# Generated by Django 5.1 on 2025-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cse", "Computer Science"),
                    ("it", "Information Technology"),
                    ("ece", "Electronics & Communication"),
                    ("eee", "Electrical & Electronics"),
                    ("mech", "Mechanical"),
                    ("civil", "Civil"),
                    ("ai_ml", "AI & Machine Learning"),
                    ("cyber_security", "Cyber Security"),
                    ("data_science", "Data Science"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
