# Generated by Django 4.2.10 on 2025-09-24 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("course_view", "Course View"),
                            ("search", "Search"),
                            ("enroll", "Course Enrollment"),
                            ("complete", "Course Completion"),
                            ("click", "Click"),
                        ],
                        max_length=20,
                    ),
                ),
                ("page_url", models.URLField()),
                ("page_title", models.CharField(max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="core_userac_user_id_fba3f1_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_userac_timesta_ac7f60_idx"
                    ),
                ],
            },
        ),
    ]
