# Generated by Django 4.2.10 on 2025-09-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="progress",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="related_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("course_view", "Course View"),
                    ("course_progress", "Course Progress"),
                    ("resource_download", "Resource Downloaded"),
                    ("forum_post", "Forum Post"),
                    ("forum_reply", "Forum Reply"),
                    ("achievement", "Achievement Unlocked"),
                    ("search", "Search"),
                    ("enroll", "Course Enrollment"),
                    ("complete", "Course Completion"),
                    ("certificate", "Certificate Earned"),
                ],
                max_length=20,
            ),
        ),
    ]
