# Generated by Django 5.1 on 2025-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("file", models.FileField(blank=True, upload_to="resources/")),
                ("download_url", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cheatsheet", "Cheat Sheet"),
                            ("template", "Code Template"),
                            ("guide", "Guide/PDF"),
                            ("external", "External Link"),
                        ],
                        max_length=100,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
